# -*- coding: utf-8 -*-
"""WesternRoulette Explore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1-gKua-uxIKXIXKP-rIEKODn9tDZ5ZY
"""

# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import the dataset
df = pd.read_csv("Parking_Transactions.csv")

df.columns

df.info()

df["Location Group"].unique()

df['Payment Method']

df.drop(columns=['Payment Method', 'Duration in Minutes', 'Source', 'Kiosk ID', 'Amount'], inplace=True)
df

df.drop_duplicates()

df['Start Time']

df['Start Time DT'] = pd.to_datetime(df["Start Time"], format="%m/%d/%Y %H:%M:%S %p")
df['Start Time DT 24'] = df["Start Time DT"].dt.strftime('%H:%M:%S')

df["Start Time DT Index"].unique()

df.set_index('Start Time DT 24', inplace=True)

df.reset_index(inplace=True, drop = True)

aggregate = df['Start Time DT 24'].resample("h").mean()

df['hour'] = df['Start Time DT 24'].dt.hour

aggregate = df.groupby('hour')
aggregate.head()

aggregate_interp = aggregate.interpolate()
aggregate_interp
df

df["Start Time DT"].shape

frequency_counts

import matplotlib.pyplot as plt
# aggregate.plot()
frequency_counts.plot()
plt.xlabel("Start Time DT")
plt.ylabel("frequency_counts")
plt.title("Occurrences Over Time")
plt.show()

from pandas.plotting import lag_plot

lag_plot(df['Start Time DT'])
plt.show()

frequency_counts = df.groupby(df[hour"])['Location Group'].value_counts()

dftest = pd.DataFrame(np.random.randn(1000, 4), index=ts.index, columns=list("ABCD"))

dftest = dftest.cumsum()

plt.figure();

df.plot();